In [85]:
import pandas as pd

df = pd.read_csv("games.csv") 
df.head()

,AppID,Name,Release date,Estimated owners,Peak CCU,Required age,Price,DiscountDLC count,About the game,Supported languages,...,Average playtime two weeks,Median playtime forever,Median playtime two weeks,Developers,Publishers,Categories,Genres,Tags,Screenshots,Movies
2539430,Black Dragon Mage Playtest,"Aug 1, 2023",0 - 0,0,0,0.00,0,0,NaN,[],...,0,0,0,NaN,NaN,NaN,NaN,NaN,https://shared.akamai.steamstatic.com/store_it...,NaN
496350,Supipara - Chapter 1 Spring Has Come!,"Jul 29, 2016",0 - 20000,0,0,5.24,65,0,"Springtime, April: when the cherry trees come ...",['English'],...,0,8,0,minori,MangaGamer,"Single-player,Steam Trading Cards,Steam Cloud,...",Adventure,"Adventure,Visual Novel,Anime,Cute",https://shared.akamai.steamstatic.com/store_it...,NaN
1034400,Mystery Solitaire The Black Raven,"May 6, 2019",0 - 20000,0,0,4.99,0,0,"Immerse yourself in the most beloved, mystical...","['English', 'French', 'German', 'Russian']",...,0,0,0,Somer Games,8floor,"Single-player,Family Sharing",Casual,"Casual,Card Game,Solitaire,Puzzle,Hidden Objec...",https://shared.akamai.steamstatic.com/store_it...,NaN
3292190,버튜버 파라노이아 - Vtuber Paranoia,"Oct 31, 2024",0 - 20000,1,0,8.99,0,1,"synopsis 'Hello, I'm Hiyoro, a new YouTuber!' ...",['Korean'],...,0,0,0,유진게임즈,유진게임즈,"Single-player,Steam Achievements,Family Sharing","Casual,Indie,Simulation",NaN,https://shared.akamai.steamstatic.com/store_it...,NaN
3631080,Maze Quest VR,"Apr 24, 2025",0 - 20000,0,0,4.99,0,0,Its not just a Maze; its a Quest! Enter the ca...,['English'],...,0,0,0,Reality Expanded LLC,Reality Expanded LLC,"Single-player,VR Only,Steam Leaderboards,Famil...","Action,Early Access",NaN,https://shared.akamai.steamstatic.com/store_it...,NaN

In [86]:
df.columns

Index(['AppID', 'Name', 'Release date', 'Estimated owners', 'Peak CCU',
       'Required age', 'Price', 'DiscountDLC count', 'About the game',
       'Supported languages', 'Full audio languages', 'Reviews',
       'Header image', 'Website', 'Support url', 'Support email', 'Windows',
       'Mac', 'Linux', 'Metacritic score', 'Metacritic url', 'User score',
       'Positive', 'Negative', 'Score rank', 'Achievements', 'Recommendations',
       'Notes', 'Average playtime forever', 'Average playtime two weeks',
       'Median playtime forever', 'Median playtime two weeks', 'Developers',
       'Publishers', 'Categories', 'Genres', 'Tags', 'Screenshots', 'Movies'],
      dtype='object')

In [87]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
Index: 122611 entries, 2539430 to 4141790
Data columns (total 39 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   AppID                       122610 non-null  object
 1   Name                        122611 non-null  object
 2   Release date                122611 non-null  object
 3   Estimated owners            122611 non-null  int64
 4   Peak CCU                    122611 non-null  int64
 5   Required age                122611 non-null  float64
 6   Price                       122611 non-null  int64
 7   DiscountDLC count           122611 non-null  int64
 8   About the game              114162 non-null  object
 9   Supported languages         122611 non-null  object
 10  Full audio languages        122611 non-null  object
 11  Reviews                     12070 non-null   object
 12  Header image                122530 non-null  object
 13  Website                     49676 non-null   object
 14  Support url                 54142 non-null   object
 15  Support email               100348 non-null  object
 16  Windows                     122611 non-null  bool
 17  Mac                         122611 non-null  bool
 18  Linux                       122611 non-null  bool
 19  Metacritic score            122611 non-null  int64
 20  Metacritic url              4256 non-null    object
 21  User score                  122611 non-null  int64
 22  Positive                    122611 non-null  int64
 23  Negative                    122611 non-null  int64
 24  Score rank                  40 non-null      float64
 25  Achievements                122611 non-null  int64
 26  Recommendations             122611 non-null  int64
 27  Notes                       22458 non-null   object
 28  Average playtime forever    122611 non-null  int64
 29  Average playtime two weeks  122611 non-null  int64
 30  Median playtime forever     122611 non-null  int64
 31  Median playtime two weeks   122611 non-null  int64
 32  Developers                  114174 non-null  object
 33  Publishers                  113702 non-null  object
 34  Categories                  113658 non-null  object
 35  Genres                      114198 non-null  object
 36  Tags                        83346 non-null   object
 37  Screenshots                 116593 non-null  object
 38  Movies                      0 non-null       float64
dtypes: bool(3), float64(3), int64(14), object(19)
memory usage: 35.0+ MB

,Estimated owners,Peak CCU,Required age,Price,DiscountDLC count,Metacritic score,User score,Positive,Negative,Score rank,Achievements,Recommendations,Average playtime forever,Average playtime two weeks,Median playtime forever,Median playtime two weeks,Movies
count,1.226110e+05,122611.000000,122611.000000,122611.000000,122611.000000,122611.000000,122611.000000,1.226110e+05,1.226110e+05,40.000000,122611.000000,1.226110e+05,1.226110e+05,122611.000000,1.226110e+05,122611.000000,0.0
mean,5.459332e+01,0.167611,4.765091,18.353663,0.545856,2.564941,0.024549,1.044986e+03,1.691974e+02,99.175000,18.087015,9.618250e+02,2.080232e+02,13.789268,1.735705e+02,14.722170,NaN
std,3.729452e+03,1.653591,12.531030,28.858970,14.516026,13.660559,1.394901,2.809173e+04,5.374645e+03,0.675107,141.493879,2.187880e+04,1.121768e+04,270.378053,1.120254e+04,294.509615,NaN
min,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,98.000000,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000,NaN
25%,0.000000e+00,0.000000,0.550000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,99.000000,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000,NaN
50%,0.000000e+00,0.000000,2.240000,0.000000,0.000000,0.000000,0.000000,5.000000e+00,1.000000e+00,99.000000,2.000000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000,NaN
75%,0.000000e+00,0.000000,5.240000,40.000000,0.000000,0.000000,0.000000,3.700000e+01,1.000000e+01,100.000000,19.000000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000,NaN
max,1.013936e+06,21.000000,999.980000,100.000000,3703.000000,97.000000,100.000000,7.642084e+06,1.173003e+06,100.000000,9821.000000,4.830455e+06,3.429544e+06,20088.000000,3.429544e+06,20088.000000,NaN

In [88]:
df.isnull().sum()

AppID                              1
Name                               0
Release date                       0
Estimated owners                   0
Peak CCU                           0
Required age                       0
Price                              0
DiscountDLC count                  0
About the game                  8449
Supported languages                0
Full audio languages               0
Reviews                       110541
Header image                      81
Website                        72935
Support url                    68469
Support email                  22263
Windows                            0
Mac                                0
Linux                              0
Metacritic score                   0
Metacritic url                118355
User score                         0
Positive                           0
Negative                           0
Score rank                    122571
Achievements                       0
Recommendations                    0
Notes                         100153
Average playtime forever           0
Average playtime two weeks         0
Median playtime forever            0
Median playtime two weeks          0
Developers                      8437
Publishers                      8909
Categories                      8953
Genres                          8413
Tags                           39265
Screenshots                     6018
Movies                        122611
dtype: int64

In [89]:
columnas_utiles = [
    "AppID",
    "Name",
    "Release date",
    "Estimated owners",
    "Price",
    "Genres",
    "Positive",
    "Negative",
    "Average playtime forever"]

df = df[columnas_utiles]

In [90]:
df.isnull().sum()

AppID                          1
Name                           0
Release date                   0
Estimated owners               0
Price                          0
Genres                      8413
Positive                       0
Negative                       0
Average playtime forever       0
dtype: int64

In [91]:
df = df.dropna(subset=["Genres"]) # limpiar nulos

In [92]:
df["Genres"] = df["Genres"].str.split(";")
df["Genres"] = df["Genres"].str[0]

In [93]:
df = df[(df["Positive"] + df["Negative"]) > 0]

df["rating"] = df["Positive"] / (df["Positive"] + df["Negative"])

In [94]:
df = df[df["Price"] >= 0] #poner precios validos

In [95]:
df.head()

,AppID,Name,Release date,Estimated owners,Price,Genres,Positive,Negative,Average playtime forever,rating
496350,Supipara - Chapter 1 Spring Has Come!,"Jul 29, 2016",0 - 20000,0,65,Adventure,252,3,8,0.988235
1034400,Mystery Solitaire The Black Raven,"May 6, 2019",0 - 20000,0,0,Casual,21,3,0,0.875000
1934300,Armored Brigade II,"Apr 8, 2025",0 - 20000,8,10,"Simulation,Strategy",117,13,675,0.900000
1157670,Hepta Beats,"May 7, 2021",0 - 20000,0,0,"Casual,Indie",28,4,0,0.875000
1540330,MUMBA IV: Egypt Jewels,"Dec 13, 2021",0 - 20000,1,0,"Action,Casual,Indie,Strategy",19,6,0,0.760000

In [96]:
#convertir rating en porcentaje
df["rating"] = df["rating"] * 100
df["rating"] = df["rating"].round(1)
df["rating"] = df["rating"].astype(str) + "%"

In [97]:
df = df[df["Average playtime forever"] > 0]

In [98]:
df.head(10)

,AppID,Name,Release date,Estimated owners,Price,Genres,Positive,Negative,Average playtime forever,rating
496350,Supipara - Chapter 1 Spring Has Come!,"Jul 29, 2016",0 - 20000,0,65,Adventure,252,3,8,98.8%
1934300,Armored Brigade II,"Apr 8, 2025",0 - 20000,8,10,"Simulation,Strategy",117,13,675,90.0%
1025440,Fantasy General II,"Sep 5, 2019",100000 - 200000,13,0,Strategy,1025,210,489,83.0%
328460,Redline,"Oct 23, 2014",0 - 20000,0,0,"Action,Racing",74,35,203,67.9%
1607040,Evertried,"Oct 21, 2021",0 - 20000,0,0,"Indie,Strategy",55,14,480,79.7%
688420,Bad North: Jotunn Edition,"Nov 16, 2018",500000 - 1000000,64,80,"Action,Indie,Simulation",11367,831,342,93.2%
657010,Lucky Night: Texas Hold'em VR,"Jul 26, 2017",100000 - 200000,0,0,"Casual,Free To Play",144,35,111,80.4%
334030,Epic Arena,"May 5, 2015",100000 - 200000,2,0,"Free To Play,Indie,Strategy",196,104,88,65.3%
830470,MazeBot,"May 3, 2018",0 - 20000,0,0,"Action,Casual,Indie",39,4,220,90.7%
416790,The Metronomicon: Slay The Dance Floor,"Sep 29, 2016",20000 - 50000,1,0,"Action,Indie,RPG",330,65,183,83.5%

In [99]:
df = df.reset_index()

In [100]:
df = df.drop(columns=['Estimated owners'])

In [101]:
df = df.rename(columns={
    'index': 'AppID',
    'AppID': 'Name',
    'Name': 'Release date',
    'Release date': 'Estimated owners'
})

In [102]:
df.head(10)

,AppID,Name,Release date,Estimated owners,Price,Genres,Positive,Negative,Average playtime forever,rating
0,496350,Supipara - Chapter 1 Spring Has Come!,"Jul 29, 2016",0 - 20000,65,Adventure,252,3,8,98.8%
1,1934300,Armored Brigade II,"Apr 8, 2025",0 - 20000,10,"Simulation,Strategy",117,13,675,90.0%
2,1025440,Fantasy General II,"Sep 5, 2019",100000 - 200000,0,Strategy,1025,210,489,83.0%
3,328460,Redline,"Oct 23, 2014",0 - 20000,0,"Action,Racing",74,35,203,67.9%
4,1607040,Evertried,"Oct 21, 2021",0 - 20000,0,"Indie,Strategy",55,14,480,79.7%
5,688420,Bad North: Jotunn Edition,"Nov 16, 2018",500000 - 1000000,80,"Action,Indie,Simulation",11367,831,342,93.2%
6,657010,Lucky Night: Texas Hold'em VR,"Jul 26, 2017",100000 - 200000,0,"Casual,Free To Play",144,35,111,80.4%
7,334030,Epic Arena,"May 5, 2015",100000 - 200000,0,"Free To Play,Indie,Strategy",196,104,88,65.3%
8,830470,MazeBot,"May 3, 2018",0 - 20000,0,"Action,Casual,Indie",39,4,220,90.7%
9,416790,The Metronomicon: Slay The Dance Floor,"Sep 29, 2016",20000 - 50000,0,"Action,Indie,RPG",330,65,183,83.5%