In [1]:
import pandas as pd

In [ ]:

df = pd.read_excel("games_limpio.xlsx")
df[['Min_Owners', 'Max_Owners']] = df['Estimated owners'].str.split(' - ', expand=True).astype(float)
df['Owners_Numeric'] = (df['Min_Owners'] + df['Max_Owners']) / 2
columnas_numericas = [
    'Price', 
    'Average playtime forever', 
    'Positive', 
    'Negative', 
    'Owners_Numeric'
]
df_final = df[['Name'] + columnas_numericas].copy()

for col in columnas_numericas:
    min_val = df_final[col].min()
    max_val = df_final[col].max()
    
    if max_val != min_val:
        df_final[f'{col}_Norm'] = ((df_final[col] - min_val) / (max_val - min_val)) * 100
    else:
        df_final[f'{col}_Norm'] = 0
df_final = df_final.dropna(subset=['Name'])
df_final = df_final.sort_values(by='Owners_Numeric', ascending=False)
display(df_final.head()) 

df_final.to_json("datos_radar.json", orient='records', indent=4)
df.head()

Mostrando las primeras columnas del archivo que se va a exportar:

,Name,Price,Average playtime forever,Positive,Negative,Owners_Numeric,Price_Norm,Average playtime forever_Norm,Positive_Norm,Negative_Norm,Owners_Numeric_Norm
8865,Counter-Strike 2,0,33906,7642084,1173003,150000000.0,0.0,0.988616,100.000000,100.000000,100.000000
763,Dota 2,0,54064,2037143,461826,150000000.0,0.0,1.576391,26.656904,39.371255,100.000000
1696,PUBG: BATTLEGROUNDS,0,23787,1520457,1037487,150000000.0,0.0,0.693562,19.895843,88.447088,100.000000
10637,Apex Legends™,0,10073,668053,326926,150000000.0,0.0,0.293683,8.741765,27.870858,100.000000
21672,Left 4 Dead 2,0,2316,940221,23762,75000000.0,0.0,0.067502,12.303202,2.025741,49.996666

,AppID,Name,Release date,Estimated owners,Price,Genres,Positive,Negative,Average playtime forever,rating,Min_Owners,Max_Owners,Owners_Numeric
0,496350,Supipara - Chapter 1 Spring Has Come!,"Jul 29, 2016",0 - 20000,65,Adventure,252,3,8,0.988,0.0,20000.0,10000.0
1,1934300,Armored Brigade II,"Apr 8, 2025",0 - 20000,10,"Simulation,Strategy",117,13,675,0.900,0.0,20000.0,10000.0
2,1025440,Fantasy General II,"Sep 5, 2019",100000 - 200000,0,Strategy,1025,210,489,0.830,100000.0,200000.0,150000.0
3,328460,Redline,"Oct 23, 2014",0 - 20000,0,"Action,Racing",74,35,203,0.679,0.0,20000.0,10000.0
4,1607040,Evertried,"Oct 21, 2021",0 - 20000,0,"Indie,Strategy",55,14,480,0.797,0.0,20000.0,10000.0